# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 2, 18, 7, 21, 6, 237000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
